name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter info
        run: |
          flutter --version
          flutter config --enable-web

      - name: Install deps
        run: flutter pub get

      - name: Ensure missing asset dirs exist
        run: mkdir -p assets/icons

      - name: Build web
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY%/*}"
          if [ "$REPO_NAME" = "${OWNER}.github.io" ]; then
            BASE="/"
          else
            BASE="/$REPO_NAME/"
          fi
          flutter build web --release --base-href "$BASE"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
